<?xml version="1.0"?>
<package format="2">
  <name>yolov7_ros</name>
  <version>1.0.0</version>
  <description>YOLOv7 cone detection ROS message package (for cross-machine interoperability)</description>
  <maintainer email="fsac@example.com">FSAC</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>message_generation</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>

  <exec_depend>message_runtime</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
</package>
