<?xml version="1.0"?>
<package format="2">
  <name>dnb_msgs</name>
  <version>0.0.1</version>
  <description>Minimal stub for pylon_camera build dependency</description>
  <maintainer email="xiaoyang@todo.todo">xiaoyang</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>std_msgs</build_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>std_msgs</exec_depend>
</package>
